//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerInfo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CRUDEntities : DbContext
    {
        public CRUDEntities()
            : base("name=CRUDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ems_ust_TradingLimits> ems_ust_TradingLimits { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNet_SqlCacheTablesForChangeNotification> AspNet_SqlCacheTablesForChangeNotification { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Calling> Callings { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
    
        public virtual ObjectResult<AspNet_SqlCachePollingStoredProcedure_Result> AspNet_SqlCachePollingStoredProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AspNet_SqlCachePollingStoredProcedure_Result>("AspNet_SqlCachePollingStoredProcedure");
        }
    
        public virtual ObjectResult<string> AspNet_SqlCacheQueryRegisteredTablesStoredProcedure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AspNet_SqlCacheQueryRegisteredTablesStoredProcedure");
        }
    
        public virtual int AspNet_SqlCacheRegisterTableStoredProcedure(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AspNet_SqlCacheRegisterTableStoredProcedure", tableNameParameter);
        }
    
        public virtual int AspNet_SqlCacheUnRegisterTableStoredProcedure(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AspNet_SqlCacheUnRegisterTableStoredProcedure", tableNameParameter);
        }
    
        public virtual int AspNet_SqlCacheUpdateChangeIdStoredProcedure(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AspNet_SqlCacheUpdateChangeIdStoredProcedure", tableNameParameter);
        }
    }
}
