//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallerInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ems_ust_TradingLimits
    {
        public string ManagerEmail { get; set; }
        public string LimitHardOrSoft { get; set; }
        public string LimitType { get; set; }
        public string LimitCurrencyCode { get; set; }
        public string LimitValue { get; set; }
        public bool LimitOverride { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    }
}
